### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by amadeu01** [Kotlin/kotlin-spec#12]
Hi, 

I know that the spec is still in development. But, I would like to know more how the garbage collection works with Kotlin and implications for Strong References.

I would like to understand better how Kotlin interacts with the garbage collector. 
When variables are ready to be destroyed, how we can manage memory leaks... 

I tried to search, but I haven't found much information.

Thanks in advance

**Comment by amadeu01** [comment]
I know there are sessions 11.6.2. | 9.9 |  18.2 | 9.7.3. 

But, all of them are still tagged as TODO 😢

**Comment by ice-phoenix** [comment]
As of now (May 2020), details of garbage collection are platform-dependent and should be covered in the respective platform-specific parts of the specification.
