### ISSUE TITLE
Not all expressions are supported condition form of the "when expression"

### ISSUE THREAD

**Issue by PetukhovVictor** [Kotlin/kotlin-spec#17]
In list of the supported condition forms of the ["when" expressions](https://github.com/JetBrains/kotlin-spec/blob/spec-rework/src/kotlin.core/expressions.md#when-expression) says in the last item, that any other expression is supported. But "continue" expression and "break" expression (without labels) can't be used. Also can't be used "spread" operator as "when" condition, which is in the "Operator expressions" section.

Maybe make a correction here?

See [this](https://github.com/PetukhovVictor/kotlin/blob/rr/petukhov/spec-tests/compiler/tests-spec/testData/diagnostics/s-16.30_when-expression/p-7/neg/5.2.kt) spec test.
(I will add a negative test for spread operators a little latter)

**Comment by ice-phoenix** [comment]
Fixed in a3ad76e
