### ISSUE TITLE
In the "Exhaustive when expressions" no says about objects, which belong to the sealed classes

### ISSUE THREAD

**Issue by PetukhovVictor** [Kotlin/kotlin-spec#18]
In the list of the cases, when "when" expression will be exhaustive says about sealed class subtypes covering using type test conditions (type test condition is type checking operator followed by type).
But we can "when" make exhaustive using just an enumeration of objects.

See [this](https://github.com/PetukhovVictor/kotlin/blob/rr/petukhov/spec-tests/compiler/tests-spec/testData/diagnostics/s-16.30_when-expression/p-11/pos/6.1.kt) spec test (case 4).

Maybe add info about exhaustive "when" written using objects, which belong to the sealed classes?

**Comment by ice-phoenix** [comment]
Fixed by @belyaev-mikhail in 545cff32
