### ISSUE TITLE
where is getCompilerTests.sh

### ISSUE THREAD

**Issue by bitcalc** [Kotlin/kotlin-spec#25]
The grammar document reads about grammar test: 

> Download compiler tests using the run script: ./getCompilerTests.sh (you must have svn installed for this);

Where can I find this script? I'd like to run the grammar test and add some testing code too.

**Comment by PetukhovVictor** [comment]
Recently, gradle task is used to downloading of compiler tests: `./gradlew :grammar:downloadCompilerTests`

Thank you for your attention! I updated the [readme](https://github.com/JetBrains/kotlin-spec/tree/master/grammar).

**Comment by bitcalc** [comment]
Another task is not found:

> /kotlin-spec$ ./gradlew :grammar:removeNewTests
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Task 'removeNewTests' not found in project ':grammar'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s

**Comment by ice-phoenix** [comment]
Sorry for a very belated response. I believe `:grammar:removeNewTests` is now called `:grammar:syncWithCompilerTests`, and we should update the README once again.

@PetukhovVictor could you confirm this?

**Comment by PetukhovVictor** [comment]
Yes, gradle task `removeNewTests` was renamed to `syncWithCompilerTests` (0644662ff600ef4886e85fc0d94487d33eaa04f6). Please use it.

I've updated the readme once again. Thanks!

**Comment by ice-phoenix** [comment]
Done
