### ISSUE TITLE
Left recursion for expression rules?

### ISSUE THREAD

**Issue by KvanTTT** [Kotlin/kotlin-spec#27]
ANTLR 4 supports left recursion. Grammar with them looks more clearly and performance of generated parser is faster.

Compare:

```antlr
expression
    : disjunction
    ;

disjunction
    : conjunction (NL* DISJ NL* conjunction)*
    ;

conjunction
    : equality (NL* CONJ NL* equality)*
    ;

equality
    : comparison (equalityOperator NL* comparison)*
    ;

... // Other rules
```

And

```antlr
expression
    : expression equalityOperator NL* expression
    | expression NL* CONJ NL* expression
    | expression NL* DISJ NL* expression
    | ... // Other alternatives including tokens
    ;
```

**Comment by belyaev-mikhail** [comment]
I think it'll be too much of a fuss to do it at this point. Our testing infrastructure tries to compare the tree to the internal compiler tree and the compiler tree is not left-recursive.

>  performance of generated parser is faster

Do you have any examples to support this claim or does it come from your experience?

**Comment by belyaev-mikhail** [comment]
Also there is this guy

```
infixOperation
    : elvisExpression (inOperator NL* elvisExpression | isOperator NL* type)*
    ;
```

I don't really know how to express this for ANTLR's left recursion magic to work. Do you?

**Comment by KvanTTT** [comment]
> Do you have any examples to support this claim or does it come from your experience?

It comes from my experience. But it's a good idea to create such samples.

**Comment by KvanTTT** [comment]
I've done some benchmarks ([AntlrLeftRecursionBenchmark](https://github.com/KvanTTT/AntlrBenchmarks/tree/master/AntlrLeftRecursionBenchmark)) and found out that left recursion is slower than ordinary recursion. That is, I changed my mind to the opposite

**Comment by KvanTTT** [comment]
The intermediate result is available: not left recursion rules are faster than left recursion ones by 15% in the worst case, see https://github.com/KvanTTT/AntlrBenchmarks#results
