### ISSUE TITLE
Using of string literals instead of token names for clarity

### ISSUE THREAD

**Issue by KvanTTT** [Kotlin/kotlin-spec#28]
Since ANTLR 4.7.2 supports linking of token names and string literal for all grammars (see https://github.com/antlr/antlr4/issues/2347), maybe it makes sense to use string literals for some tokens like `LPAREN`, `COMMA` and similar for clarity?

Compare the following rule:

```antlr
ifExpression
    : IF NL* LPAREN NL* expression NL* RPAREN NL* (controlStructureBody | SEMICOLON)
    | IF NL* LPAREN NL* expression NL* RPAREN NL* controlStructureBody? NL* SEMICOLON? NL* ELSE NL* (controlStructureBody | SEMICOLON)
    ;
```

And the following with string literals:

```antlr
ifExpression
    : IF NL* '(' NL* expression NL* ')' NL* (controlStructureBody | ';')
    | IF NL* '(' NL* expression NL* ')' NL* controlStructureBody? NL* ';'? NL* ELSE NL* (controlStructureBody | ';')
    ;
```

ANTLR generates identical code for both grammars.

**Comment by belyaev-mikhail** [comment]
Well, I totally agree with you on this one. Even more, my original grammar (the one I submitted to antlr repo) had string literals where applicable.
But the team decided to change them back for some reason.

**Comment by wmeints** [comment]
I'm working on a .NET version of the Kotlin compiler and don't really care whether you use string literals or symbols. But if you look at Antlr, it's generally a good practice to use lexer tokens instead of literals.

**Comment by KvanTTT** [comment]
> But if you look at Antlr, it's generally a good practice to use lexer tokens instead of literals.

Where should I look at? In general, it depends on the code style in a concrete project.
