### ISSUE TITLE
Html version of the specification is not available on 

### ISSUE THREAD

**Issue by phront** [Kotlin/kotlin-spec#31]
Got html error 404 on requesting link to html artifact http://jetbrains.github.io/kotlin-spec/

**Comment by PetukhovVictor** [comment]
Html version of the spec is available on https://github.com/Kotlin/kotlin-spec
We are fixed link in the repo main page. Thx!

**Comment by jnorthrup** [comment]
is it out of the question to request the link in the README @petukhovv ?
