### ISSUE TITLE
Inconsistent formatting for rule alternatives

### ISSUE THREAD

**Issue by KvanTTT** [Kotlin/kotlin-spec#36]
The following alternatives are declared without line breaks:

```antlr
additiveOperator
    : ADD | SUB
    ;
```

But the following - with line breaks:

```antlr
multiplicativeOperator
    : MULT
    | DIV
    | MOD
    ;
```

I suggest always using line breaks for rule alternatives.

**Comment by PetukhovVictor** [comment]
In the next iteration of improving the grammar, we will try to bring the formatting to a consistent look. Thank you for your attention!
