### ISSUE TITLE
ANTLR parser fails when a newline exists inside an expression interpolated in a string

### ISSUE THREAD

**Issue by ondrej** [Kotlin/kotlin-spec#40]
Hi team,

I noticed a problem when parsing files using the official Kotlin ANTLR grammar from https://kotlinlang.org/docs/reference/grammar.html.

This parses OK:
```kotlin
val numbers = mapOf("1" to 1, "2" to 2, "3" to 3)
println("output: ${numbers.entries.joinToString { "${it.key}: ${it.value}" }}")
```

This fails (but compiles without issue in e.g. Android Studio):
```kotlin
val numbers = mapOf("1" to 1, "2" to 2, "3" to 3)
println("output: ${
    numbers.entries.joinToString { "${it.key}: ${it.value}" }}")
```

This issue is possibly related to https://youtrack.jetbrains.com/issue/KT-26077. When adding parentheses around the expression, ANTRL does parse the statement just fine. Assuming this is the same issue, and since KT-26077 hasn't been touched in over a year, is there anything I might be able to do in the short term to work around this?

Many thanks!

**Comment by drieks** [comment]
Hi,

@arkadiuszpalka found the same problem in https://github.com/kotlinx/ast/issues/31. The fix is to add NL* inside of lineStringExpression:

https://github.com/kotlinx/ast/commit/e574d67170c34b451680b49241429855593eda47

**Comment by belyaev-mikhail** [comment]
Just for the record: KT-26077 is not planned to be fixed in ANTLR grammar at all because it comes from basic inconsistency of Kotlin lexical structure with traditional lexer/parser dichotomy. This issue, though, is not related and seems to be fixed by #77.

**Comment by lbtrace** [comment]
@drieks I have a question for you, can you tell me? Is it only ANTLR grammar file kotlinParser.g4 bug? kotlinc compiler always process NL* inside of lineStringExpression, right?

**Comment by drieks** [comment]
Hi @lbtrace,
yes, it's related to the antlr grammar here: https://kotlinlang.org/docs/reference/grammar.html.
The Kotlin Compile is not using this grammar and is therefore not affected.
