### ISSUE TITLE
downloading ideaIC-LATEST-EAP-SNAPSHOT.zip?

### ISSUE THREAD

**Issue by bitcalc** [Kotlin/kotlin-spec#45]
Hi,

When I run the grammar test, I have noticed that Gradle downloads the large file ideaIC-LATEST-EAP-SNAPSHOT.zip automatically from time to time when there is an update. Is the IDE package mandatory to run the tests? Is there a way to disable the downloading?

Thank you.

**Comment by petukhovv** [comment]
@bitcalc `ideaIC` is required for tests infrastructure.

Quote from readme:
> When doing the build for the very first time, you will see Gradle downloading ideaIC-LATEST-EAP-SNAPSHOT.zip, which may take quite a long time. This IDEA snapshot is used for specification and grammar tests, and will be cached (until a new version is available), so this lengthy download should happen only once (in a while).

Also, if you aren't going to use the grammar subproject, you can set gradle property (see `gradle.properties`) `withGrammarProject` to `false`, then `ideaIC` won't be loaded.
